<a href="https://colab.research.google.com/github/sayaliph18/project/blob/main/model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [ ]:
# sklearn modules for preprocessing
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
# from imblearn.over_sampling import SMOTE  # SMOTE
# sklearn modules for ML model selection
from sklearn.model_selection import train_test_split  # import 'train_test_split'
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# Libraries for data modelling
from sklearn import svm, tree, linear_model, neighbors
from sklearn import naive_bayes, ensemble, discriminant_analysis, gaussian_process
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier

# Common sklearn Model Helpers
from sklearn import feature_selection
from sklearn import model_selection
from sklearn import metrics
# from sklearn.datasets import make_classification

# sklearn modules for performance metrics
from sklearn.metrics import confusion_matrix, classification_report, precision_recall_curve
from sklearn.metrics import auc, roc_auc_score, roc_curve, recall_score, log_loss
from sklearn.metrics import f1_score, accuracy_score, roc_auc_score, make_scorer
from sklearn.metrics import average_precision_score

In [ ]:
df1 = pd.read_excel('sample_profile_data.xlsx')

df2 = pd.read_csv('sample_loan_data.csv')

df3 = pd.read_parquet('sample_users_transactions.parquet')

In [ ]:
merged_df = pd.merge(df1, df2, left_on='profile_user_id', right_on='loan_user_id', how='inner')

In [ ]:
df = pd.merge(merged_df, df3, left_on='profile_user_id', right_on='trans_user_id', how='inner')
df

,profile_user_id,profile_birth_date,profile_city,profile_residence_state,profile_registerd_device,loan_id,loan_user_id,loan_amount,loan_repay_date,loan_repay_extended_date,...,loan_created_at,trans_id,trans_user_id,trans_name,trans_amount,trans_after_balance,trans_date,trans_personal_category,trans_personal_cat_details,trans_created_at
0,50620,1982-03-21,Villa Rica,Georgia,ios,501016,50620,55.0,2022-06-08,NaN,...,2022-05-09 12:30:04,24787942,50620,Shell,56.00,225.57,2022-01-03,TRANSPORTATION,TRANSPORTATION_GAS,2022-05-19 13:52:05
1,50620,1982-03-21,Villa Rica,Georgia,ios,501016,50620,55.0,2022-06-08,NaN,...,2022-05-09 12:30:04,24787954,50620,Shell,10.60,214.97,2022-01-03,TRANSPORTATION,TRANSPORTATION_GAS,2022-05-19 13:52:05
2,50620,1982-03-21,Villa Rica,Georgia,ios,501016,50620,55.0,2022-06-08,NaN,...,2022-05-09 12:30:04,24787966,50620,PEACHTREE BREAKR V 01-02 MARIETTA GA 4662 DEBI...,2.60,212.37,2022-01-03,TRANSFER_OUT,TRANSFER_OUT_ACCOUNT_TRANSFER,2022-05-19 13:52:05
3,50620,1982-03-21,Villa Rica,Georgia,ios,501016,50620,55.0,2022-06-08,NaN,...,2022-05-09 12:30:04,24787979,50620,PEACHTREE BREAKR V 01-02 MARIETTA GA 4662 DEBI...,2.10,210.27,2022-01-03,TRANSFER_OUT,TRANSFER_OUT_ACCOUNT_TRANSFER,2022-05-19 13:52:05
4,50620,1982-03-21,Villa Rica,Georgia,ios,501016,50620,55.0,2022-06-08,NaN,...,2022-05-09 12:30:04,24787989,50620,McDonald's,6.46,203.81,2022-01-03,FOOD_AND_DRINK,FOOD_AND_DRINK_FAST_FOOD,2022-05-19 13:52:05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2199828,786189,NaT,NaN,Michigan,ios,533443,786189,30.0,2022-07-03,NaN,...,2022-06-03 06:37:23,61232302,786189,ALBERT SAVINGS 54294096 WEB ID: 853986782,7.00,915.88,2022-06-06,TRANSFER_OUT,TRANSFER_OUT_SAVINGS,2022-06-07 18:58:24
2199829,786189,NaT,NaN,Michigan,ios,533443,786189,30.0,2022-07-03,NaN,...,2022-06-03 06:37:23,61232303,786189,7-Eleven,4.78,911.10,2022-06-06,GENERAL_MERCHANDISE,GENERAL_MERCHANDISE_CONVENIENCE_STORES,2022-06-07 18:58:24
2199830,786189,NaT,NaN,Michigan,ios,533443,786189,30.0,2022-07-03,NaN,...,2022-06-03 06:37:23,61232304,786189,7-Eleven,2.99,908.11,2022-06-06,GENERAL_MERCHANDISE,GENERAL_MERCHANDISE_CONVENIENCE_STORES,2022-06-07 18:58:24
2199831,786189,NaT,NaN,Michigan,ios,533443,786189,30.0,2022-07-03,NaN,...,2022-06-03 06:37:23,61232305,786189,60147 - RENAISSANCE CTR DETROIT MI 06/03,15.00,893.11,2022-06-06,TRAVEL,TRAVEL_LODGING,2022-06-07 18:58:24
2199832,786189,NaT,NaN,Michigan,ios,533443,786189,30.0,2022-07-03,NaN,...,2022-06-03 06:37:23,61232306,786189,POS DEBIT SC WEB PAYMENTS,300.00,593.11,2022-06-07,TRANSFER_OUT,TRANSFER_OUT_ACCOUNT_TRANSFER,2022-06-07 18:58:24

In [ ]:
df.head()

,profile_user_id,profile_birth_date,profile_city,profile_residence_state,profile_registerd_device,loan_id,loan_user_id,loan_amount,loan_repay_date,loan_repay_extended_date,...,loan_created_at,trans_id,trans_user_id,trans_name,trans_amount,trans_after_balance,trans_date,trans_personal_category,trans_personal_cat_details,trans_created_at
0,50620,1982-03-21,Villa Rica,Georgia,ios,501016,50620,55.0,2022-06-08,NaN,...,2022-05-09 12:30:04,24787942,50620,Shell,56.00,225.57,2022-01-03,TRANSPORTATION,TRANSPORTATION_GAS,2022-05-19 13:52:05
1,50620,1982-03-21,Villa Rica,Georgia,ios,501016,50620,55.0,2022-06-08,NaN,...,2022-05-09 12:30:04,24787954,50620,Shell,10.60,214.97,2022-01-03,TRANSPORTATION,TRANSPORTATION_GAS,2022-05-19 13:52:05
2,50620,1982-03-21,Villa Rica,Georgia,ios,501016,50620,55.0,2022-06-08,NaN,...,2022-05-09 12:30:04,24787966,50620,PEACHTREE BREAKR V 01-02 MARIETTA GA 4662 DEBI...,2.60,212.37,2022-01-03,TRANSFER_OUT,TRANSFER_OUT_ACCOUNT_TRANSFER,2022-05-19 13:52:05
3,50620,1982-03-21,Villa Rica,Georgia,ios,501016,50620,55.0,2022-06-08,NaN,...,2022-05-09 12:30:04,24787979,50620,PEACHTREE BREAKR V 01-02 MARIETTA GA 4662 DEBI...,2.10,210.27,2022-01-03,TRANSFER_OUT,TRANSFER_OUT_ACCOUNT_TRANSFER,2022-05-19 13:52:05
4,50620,1982-03-21,Villa Rica,Georgia,ios,501016,50620,55.0,2022-06-08,NaN,...,2022-05-09 12:30:04,24787989,50620,McDonald's,6.46,203.81,2022-01-03,FOOD_AND_DRINK,FOOD_AND_DRINK_FAST_FOOD,2022-05-19 13:52:05

In [ ]:
df.shape

(2199833, 21)

## Data Preprocessing

dropping first unknown column

In [ ]:
df.columns

Index(['profile_user_id', 'profile_birth_date', 'profile_city',
       'profile_residence_state', 'profile_registerd_device', 'loan_id',
       'loan_user_id', 'loan_amount', 'loan_repay_date',
       'loan_repay_extended_date', 'loan_status', 'loan_created_at',
       'trans_id', 'trans_user_id', 'trans_name', 'trans_amount',
       'trans_after_balance', 'trans_date', 'trans_personal_category',
       'trans_personal_cat_details', 'trans_created_at'],
      dtype='object')

profile_birth_date has total 2261 missing value and for profile_city we have total 2435 missing values.hence we drop this columns

In [ ]:
columns_to_drop = ['profile_birth_date', 'profile_city','loan_repay_extended_date']
df.drop(columns_to_drop, axis=1, inplace=True)

In [ ]:
df.head()

,profile_user_id,profile_residence_state,profile_registerd_device,loan_id,loan_user_id,loan_amount,loan_repay_date,loan_status,loan_created_at,trans_id,trans_user_id,trans_name,trans_amount,trans_after_balance,trans_date,trans_personal_category,trans_personal_cat_details,trans_created_at
0,50620,Georgia,ios,501016,50620,55.0,2022-06-08,2,2022-05-09 12:30:04,24787942,50620,Shell,56.00,225.57,2022-01-03,TRANSPORTATION,TRANSPORTATION_GAS,2022-05-19 13:52:05
1,50620,Georgia,ios,501016,50620,55.0,2022-06-08,2,2022-05-09 12:30:04,24787954,50620,Shell,10.60,214.97,2022-01-03,TRANSPORTATION,TRANSPORTATION_GAS,2022-05-19 13:52:05
2,50620,Georgia,ios,501016,50620,55.0,2022-06-08,2,2022-05-09 12:30:04,24787966,50620,PEACHTREE BREAKR V 01-02 MARIETTA GA 4662 DEBI...,2.60,212.37,2022-01-03,TRANSFER_OUT,TRANSFER_OUT_ACCOUNT_TRANSFER,2022-05-19 13:52:05
3,50620,Georgia,ios,501016,50620,55.0,2022-06-08,2,2022-05-09 12:30:04,24787979,50620,PEACHTREE BREAKR V 01-02 MARIETTA GA 4662 DEBI...,2.10,210.27,2022-01-03,TRANSFER_OUT,TRANSFER_OUT_ACCOUNT_TRANSFER,2022-05-19 13:52:05
4,50620,Georgia,ios,501016,50620,55.0,2022-06-08,2,2022-05-09 12:30:04,24787989,50620,McDonald's,6.46,203.81,2022-01-03,FOOD_AND_DRINK,FOOD_AND_DRINK_FAST_FOOD,2022-05-19 13:52:05

for profile_residence_state column has 25 missing values.

In [ ]:
# Calculate the mode of the 'Category' column
mode_category = df['profile_residence_state'].mode()[0]

# Fill missing values in the 'Category' column with the mode
df['profile_residence_state'].fillna(mode_category, inplace=True)

In [ ]:
# Dropping rows with missing values for specific columns permanently
columns_to_check = ['trans_name', 'trans_personal_category','trans_personal_cat_details']  # Specify columns to check for missing values
df.dropna(subset=columns_to_check, inplace=True)  # Drop rows with missing values for specified columns

In [ ]:
df.isna().sum()

profile_user_id               0
profile_residence_state       0
profile_registerd_device      0
loan_id                       0
loan_user_id                  0
loan_amount                   0
loan_repay_date               0
loan_status                   0
loan_created_at               0
trans_id                      0
trans_user_id                 0
trans_name                    0
trans_amount                  0
trans_after_balance           0
trans_date                    0
trans_personal_category       0
trans_personal_cat_details    0
trans_created_at              0
dtype: int64

#Removing outliers

trans_amount,trans_after_balance columns has outliers.

In [ ]:
# Calculate the mean of the 'trans_amount' column
mean_numeric_column = df['trans_amount'].mean()
mean_numeric_column
# Fill missing values in the 'Numeric_Column' column with the mean
df['trans_amount'].fillna(mean_numeric_column, inplace=True)

In [ ]:
mean_numeric_column1 = df['trans_after_balance'].mean()
mean_numeric_column1
# Fill missing values in the 'Numeric_Column' column with the mean
df['trans_after_balance'].fillna(mean_numeric_column1, inplace=True)

In [ ]:
df.dtypes

profile_user_id                        int64
profile_residence_state               object
profile_registerd_device              object
loan_id                                int64
loan_user_id                           int64
loan_amount                          float64
loan_repay_date                       object
loan_status                            int64
loan_created_at                       object
trans_id                               int64
trans_user_id                          int64
trans_name                            object
trans_amount                         float64
trans_after_balance                  float64
trans_date                            object
trans_personal_category               object
trans_personal_cat_details            object
trans_created_at              datetime64[us]
dtype: object

In [ ]:
# Find out multiple categorical columns
categorical_columns = df.select_dtypes(include=['object']).columns

# Displaying the list of categorical columns
print("Categorical columns:", list(categorical_columns))

Categorical columns: ['profile_residence_state', 'profile_registerd_device', 'loan_repay_date', 'loan_created_at', 'trans_name', 'trans_date', 'trans_personal_category', 'trans_personal_cat_details']

In [ ]:
# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Apply LabelEncoder to multiple categorical columns and overwrite the existing columns
for column in ['profile_residence_state', 'trans_name', 'trans_personal_category', 'trans_personal_cat_details']:
    df[column] = label_encoder.fit_transform(df[column])

# Display the encoded DataFrame
df.head()

,profile_user_id,profile_residence_state,profile_registerd_device,loan_id,loan_user_id,loan_amount,loan_repay_date,loan_status,loan_created_at,trans_id,trans_user_id,trans_name,trans_amount,trans_after_balance,trans_date,trans_personal_category,trans_personal_cat_details,trans_created_at
0,50620,10,ios,501016,50620,55.0,2022-06-08,2,2022-05-09 12:30:04,24787942,50620,982262,56.00,225.57,2022-01-03,16,88,2022-05-19 13:52:05
1,50620,10,ios,501016,50620,55.0,2022-06-08,2,2022-05-09 12:30:04,24787954,50620,982262,10.60,214.97,2022-01-03,16,88,2022-05-19 13:52:05
2,50620,10,ios,501016,50620,55.0,2022-06-08,2,2022-05-09 12:30:04,24787966,50620,664112,2.60,212.37,2022-01-03,15,82,2022-05-19 13:52:05
3,50620,10,ios,501016,50620,55.0,2022-06-08,2,2022-05-09 12:30:04,24787979,50620,664112,2.10,210.27,2022-01-03,15,82,2022-05-19 13:52:05
4,50620,10,ios,501016,50620,55.0,2022-06-08,2,2022-05-09 12:30:04,24787989,50620,582903,6.46,203.81,2022-01-03,3,15,2022-05-19 13:52:05

In [ ]:
# Initialize OneHotEncoder
onehot_encoder = OneHotEncoder(sparse=False)

# Apply OneHotEncoder to the 'Category' column and overwrite the original column
encoded_categories = onehot_encoder.fit_transform(df[['profile_registerd_device']])
encoded_df = pd.DataFrame(encoded_categories, columns=onehot_encoder.get_feature_names_out(['profile_registerd_device']))
df.drop('profile_registerd_device', axis=1, inplace=True)  # Drop the original column
df[encoded_df.columns] = encoded_df  # Assign the encoded values to the original column names

In [ ]:
df.head()

,profile_user_id,profile_residence_state,loan_id,loan_user_id,loan_amount,loan_repay_date,loan_status,loan_created_at,trans_id,trans_user_id,trans_name,trans_amount,trans_after_balance,trans_date,trans_personal_category,trans_personal_cat_details,trans_created_at,profile_registerd_device_android,profile_registerd_device_ios
0,50620,10,501016,50620,55.0,2022-06-08,2,2022-05-09 12:30:04,24787942,50620,982262,56.00,225.57,2022-01-03,16,88,2022-05-19 13:52:05,0.0,1.0
1,50620,10,501016,50620,55.0,2022-06-08,2,2022-05-09 12:30:04,24787954,50620,982262,10.60,214.97,2022-01-03,16,88,2022-05-19 13:52:05,0.0,1.0
2,50620,10,501016,50620,55.0,2022-06-08,2,2022-05-09 12:30:04,24787966,50620,664112,2.60,212.37,2022-01-03,15,82,2022-05-19 13:52:05,0.0,1.0
3,50620,10,501016,50620,55.0,2022-06-08,2,2022-05-09 12:30:04,24787979,50620,664112,2.10,210.27,2022-01-03,15,82,2022-05-19 13:52:05,0.0,1.0
4,50620,10,501016,50620,55.0,2022-06-08,2,2022-05-09 12:30:04,24787989,50620,582903,6.46,203.81,2022-01-03,3,15,2022-05-19 13:52:05,0.0,1.0

In [ ]:
df['loan_status'].replace({2: 0, 7: 1}, inplace=True)

In [ ]:
df.head()

,profile_user_id,profile_residence_state,loan_id,loan_user_id,loan_amount,loan_repay_date,loan_status,loan_created_at,trans_id,trans_user_id,trans_name,trans_amount,trans_after_balance,trans_date,trans_personal_category,trans_personal_cat_details,trans_created_at,profile_registerd_device_android,profile_registerd_device_ios
0,50620,10,501016,50620,55.0,2022-06-08,0,2022-05-09 12:30:04,24787942,50620,982262,56.00,225.57,2022-01-03,16,88,2022-05-19 13:52:05,0.0,1.0
1,50620,10,501016,50620,55.0,2022-06-08,0,2022-05-09 12:30:04,24787954,50620,982262,10.60,214.97,2022-01-03,16,88,2022-05-19 13:52:05,0.0,1.0
2,50620,10,501016,50620,55.0,2022-06-08,0,2022-05-09 12:30:04,24787966,50620,664112,2.60,212.37,2022-01-03,15,82,2022-05-19 13:52:05,0.0,1.0
3,50620,10,501016,50620,55.0,2022-06-08,0,2022-05-09 12:30:04,24787979,50620,664112,2.10,210.27,2022-01-03,15,82,2022-05-19 13:52:05,0.0,1.0
4,50620,10,501016,50620,55.0,2022-06-08,0,2022-05-09 12:30:04,24787989,50620,582903,6.46,203.81,2022-01-03,3,15,2022-05-19 13:52:05,0.0,1.0

In [ ]:
columns_to_drop = ['loan_repay_date', 'loan_created_at','trans_date','trans_created_at']
df.drop(columns_to_drop, axis=1, inplace=True)

In [ ]:
df.shape

(2199826, 15)

drop same frature with different column name

In [ ]:
columns_to_drop = ['loan_user_id', 'trans_user_id']
df.drop(columns_to_drop, axis=1, inplace=True)

In [ ]:
# Dropping rows with missing values for specific columns permanently
columns_to_check = ['profile_registerd_device_android', 'profile_registerd_device_ios']  # Specify columns to check for missing values
df.dropna(subset=columns_to_check, inplace=True)  # Drop rows with missing values for specified columns

In [ ]:
df.shape

(2199819, 13)

In [ ]:
df.isna().sum()

profile_user_id                     0
profile_residence_state             0
loan_id                             0
loan_amount                         0
loan_status                         0
trans_id                            0
trans_name                          0
trans_amount                        0
trans_after_balance                 0
trans_personal_category             0
trans_personal_cat_details          0
profile_registerd_device_android    0
profile_registerd_device_ios        0
dtype: int64

In [ ]:
df.head()

,profile_user_id,profile_residence_state,loan_id,loan_amount,loan_status,trans_id,trans_name,trans_amount,trans_after_balance,trans_personal_category,trans_personal_cat_details,profile_registerd_device_android,profile_registerd_device_ios
0,50620,10,501016,55.0,0,24787942,982262,56.00,225.57,16,88,0.0,1.0
1,50620,10,501016,55.0,0,24787954,982262,10.60,214.97,16,88,0.0,1.0
2,50620,10,501016,55.0,0,24787966,664112,2.60,212.37,15,82,0.0,1.0
3,50620,10,501016,55.0,0,24787979,664112,2.10,210.27,15,82,0.0,1.0
4,50620,10,501016,55.0,0,24787989,582903,6.46,203.81,3,15,0.0,1.0

In [ ]:
df1 = df.copy()
df1.head()

,profile_user_id,profile_residence_state,loan_id,loan_amount,loan_status,trans_id,trans_name,trans_amount,trans_after_balance,trans_personal_category,trans_personal_cat_details,profile_registerd_device_android,profile_registerd_device_ios
0,50620,10,501016,55.0,0,24787942,982262,56.00,225.57,16,88,0.0,1.0
1,50620,10,501016,55.0,0,24787954,982262,10.60,214.97,16,88,0.0,1.0
2,50620,10,501016,55.0,0,24787966,664112,2.60,212.37,15,82,0.0,1.0
3,50620,10,501016,55.0,0,24787979,664112,2.10,210.27,15,82,0.0,1.0
4,50620,10,501016,55.0,0,24787989,582903,6.46,203.81,3,15,0.0,1.0

# Feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
target=df1['loan_status']
data = df1.drop(columns=['loan_status'])
# Extract numeric columns for scaling
numeric_columns = data.select_dtypes(include=['number']).columns

# Initialize StandardScaler
scaler = StandardScaler()

# Scale only the numeric columns
data[numeric_columns] = scaler.fit_transform(data[numeric_columns])

df1 = pd.concat([data, target], axis=1)
# Display (the scaled DataFrame
df1.head()

,profile_user_id,profile_residence_state,loan_id,loan_amount,trans_id,trans_name,trans_amount,trans_after_balance,trans_personal_category,trans_personal_cat_details,profile_registerd_device_android,profile_registerd_device_ios,loan_status
0,-4.523154,-0.882218,-0.036023,0.213711,-0.621956,1.208794,0.120874,-0.173500,1.172052,1.103708,-0.415316,0.415316,0
1,-4.523154,-0.882218,-0.036023,0.213711,-0.621955,1.208794,0.021696,-0.178116,1.172052,1.103708,-0.415316,0.415316,0
2,-4.523154,-0.882218,-0.036023,0.213711,-0.621954,0.256761,0.004220,-0.179248,0.991834,0.906932,-0.415316,0.415316,0
3,-4.523154,-0.882218,-0.036023,0.213711,-0.621953,0.256761,0.003128,-0.180162,0.991834,0.906932,-0.415316,0.415316,0
4,-4.523154,-0.882218,-0.036023,0.213711,-0.621952,0.013750,0.012652,-0.182975,-1.170780,-1.290395,-0.415316,0.415316,0

In [ ]:
#df.to_csv('scaled_data.csv', index=False)

In [ ]:
X = df1.drop(columns=['loan_status'])
y = df1['loan_status']

In [ ]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: loan_status, dtype: int64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.25,
                                                    random_state=7)
print("Number transactions X_train dataset: ", X_train.shape)
print("Number transactions y_train dataset: ", y_train.shape)
print("Number transactions X_test dataset: ", X_test.shape)
print("Number transactions y_test dataset: ", y_test.shape)

Number transactions X_train dataset:  (1649864, 12)
Number transactions y_train dataset:  (1649864,)
Number transactions X_test dataset:  (549955, 12)
Number transactions y_test dataset:  (549955,)

# Building Machine Learning Models

In [ ]:
df.isna().sum()

profile_user_id                     0
profile_residence_state             0
loan_id                             0
loan_amount                         0
loan_status                         0
trans_id                            0
trans_name                          0
trans_amount                        0
trans_after_balance                 0
trans_personal_category             0
trans_personal_cat_details          0
profile_registerd_device_android    0
profile_registerd_device_ios        0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2199819 entries, 0 to 2199825
Data columns (total 13 columns):
 #   Column                            Dtype
---  ------                            -----
 0   profile_user_id                   int64
 1   profile_residence_state           int64
 2   loan_id                           int64
 3   loan_amount                       float64
 4   loan_status                       int64
 5   trans_id                          int64
 6   trans_name                        int64
 7   trans_amount                      float64
 8   trans_after_balance               float64
 9   trans_personal_category           int64
 10  trans_personal_cat_details        int64
 11  profile_registerd_device_android  float64
 12  profile_registerd_device_ios      float64
dtypes: float64(5), int64(8)
memory usage: 235.0 MB

In [ ]:
df.shape

(2199819, 13)

# Feature selection

In [ ]:
from sklearn.feature_selection import SelectKBest, f_classif
# Perform feature selection
# SelectKBest with f_classif score function (suitable for classification problems)
selector = SelectKBest(score_func=f_classif, k=10)  # Select top 12 features
X_train_selected = selector.fit_transform(X_train, y_train)
X_test_selected = selector.transform(X_test)

# Now, X_train_selected and X_test_selected contain only the selected features

# Initialize and train a classification model using the selected features
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train_selected, y_train)

# Make predictions on the test set using the model with selected features
y_pred = clf.predict(X_test_selected)

In [ ]:
# Logistic Regression
log_reg = LogisticRegression()
log_reg.fit(X_train_selected, y_train)
log_reg_pred = log_reg.predict(X_test_selected)
log_reg_accuracy = accuracy_score(y_test, log_reg_pred)
print("Logistic Regression Accuracy:", log_reg_accuracy)

# Random Forest
rf = RandomForestClassifier()
rf.fit(X_train_selected, y_train)
rf_pred = rf.predict(X_test_selected)
rf_accuracy = accuracy_score(y_test, rf_pred)
print("Random Forest Accuracy:", rf_accuracy)


# Decision Tree
dt = DecisionTreeClassifier()
dt.fit(X_train_selected, y_train)
dt_pred = dt.predict(X_test_selected)
dt_accuracy = accuracy_score(y_test, dt_pred)
print("Decision Tree Accuracy:", dt_accuracy)

# XGBoost
xgb_classifier = xgb.XGBClassifier()
xgb_classifier.fit(X_train_selected, y_train)
xgb_pred = xgb_classifier.predict(X_test_selected)
xgb_accuracy = accuracy_score(y_test, xgb_pred)
print("XGBoost Accuracy:", xgb_accuracy)

# Support Vector Machine
svm = SVC()
svm.fit(X_train_selected, y_train)
svm_pred = svm.predict(X_test_selected)
svm_accuracy = accuracy_score(y_test, svm_pred)
print("SVM Accuracy:", svm_accuracy)

Logistic Regression Accuracy: 0.8386413433826404
Random Forest Accuracy: 0.9999254484457819
Decision Tree Accuracy: 0.9997417970561228
XGBoost Accuracy: 0.9819057922920966